# Generated by Django 6.0.2 on 2026-02-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
